package com.scanit.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.scanit.dto.ReceiptDtos.*;
import com.scanit.entity.Receipt;
import com.scanit.exception.ApiException;
import com.scanit.repository.ReceiptRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.mail.MailException;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Optional;

@Service
public class ReceiptService {

    private static final Logger logger = LoggerFactory.getLogger(ReceiptService.class);
    
    private final ReceiptRepository receiptRepository;
    private final JavaMailSender mailSender;
    private final ObjectMapper objectMapper;

    public ReceiptService(ReceiptRepository receiptRepository, 
                         Optional<JavaMailSender> mailSender,
                         ObjectMapper objectMapper) {
        this.receiptRepository = receiptRepository;
        this.mailSender = mailSender.orElse(null);
        this.objectMapper = objectMapper;
    }

    @Transactional
    public ReceiptResponse generateReceipt(GenerateReceiptRequest request) {
        // Validate request
        if (request.businessId() == null || request.businessId().isBlank()) {
            throw new ApiException(400, "Business ID is required");
        }
        if (request.amount() == null || request.amount().compareTo(BigDecimal.ZERO) <= 0) {
            throw new ApiException(400, "Amount must be greater than zero");
        }

        // Create receipt entity
        Receipt receipt = new Receipt();
        
        // Receipt number will be generated by database trigger
        // Do NOT set receiptNumber here - let the DB trigger handle it
        
        // Payment references
        receipt.setOrderId(request.orderId());
        receipt.setTicketId(request.ticketId());
        receipt.setQuickPaymentId(request.quickPaymentId());
        receipt.setDevicePaymentId(request.devicePaymentId());
        
        // Business details
        receipt.setBusinessId(request.businessId());
        receipt.setBusinessName(request.businessName() != null ? request.businessName() : "Unknown Business");
        receipt.setMerchantId(request.merchantId() != null ? request.merchantId() : request.businessId());
        
        // Customer details
        receipt.setCustomerName(request.customerName());
        receipt.setCustomerEmail(request.customerEmail());
        receipt.setCustomerPhone(request.customerPhone());
        
        // Payment details
        receipt.setAmount(request.amount());
        receipt.setCurrency(request.currency() != null ? request.currency() : "UGX");
        receipt.setPaymentMethod(request.paymentMethod());
        receipt.setPaymentReference(request.paymentReference());
        receipt.setPaymentDate(LocalDateTime.now());
        
        // Items (convert to JSON)
        if (request.items() != null && !request.items().isEmpty()) {
            try {
                receipt.setItems(objectMapper.writeValueAsString(request.items()));
            } catch (JsonProcessingException e) {
                logger.error("Failed to serialize receipt items", e);
            }
        }
        
        // Calculate totals
        BigDecimal subtotal = request.subtotal() != null ? request.subtotal() : request.amount();
        BigDecimal taxAmount = request.taxAmount() != null ? request.taxAmount() : BigDecimal.ZERO;
        BigDecimal serviceFee = request.serviceFee() != null ? request.serviceFee() : BigDecimal.ZERO;
        BigDecimal totalAmount = subtotal.add(taxAmount).add(serviceFee);
        
        receipt.setSubtotal(subtotal);
        receipt.setTaxAmount(taxAmount);
        receipt.setServiceFee(serviceFee);
        receipt.setTotalAmount(totalAmount);
        
        // Metadata
        receipt.setNotes(request.notes());
        receipt.setStatus(Receipt.ReceiptStatus.GENERATED);
        
        // Save receipt - flush to get the generated receipt number from DB
        receipt = receiptRepository.saveAndFlush(receipt);
        
        // Refresh to get the generated receipt number from the database trigger
        receiptRepository.refresh(receipt);
        
        // Auto-send email if requested and email is provided
        if (Boolean.TRUE.equals(request.sendEmail()) && request.customerEmail() != null && !request.customerEmail().isBlank()) {
            try {
                sendReceiptEmail(receipt.getReceiptNumber(), request.customerEmail());
            } catch (Exception e) {
                logger.error("Failed to send receipt email for {}", receipt.getReceiptNumber(), e);
                // Don't fail the receipt generation if email fails
            }
        }
        
        logger.info("Generated receipt {} for business {}", receipt.getReceiptNumber(), receipt.getBusinessId());
        
        return toResponse(receipt);
    }

    @Transactional
    public EmailSendResult sendReceiptEmail(String receiptNumber, String recipientEmail) {
        Receipt receipt = receiptRepository.findByReceiptNumber(receiptNumber)
                .orElseThrow(() -> new ApiException(404, "Receipt not found"));
        
        if (mailSender == null) {
            logger.warn("Email service not configured. Marking receipt as sent without actually sending.");
            receipt.setEmailSent(true);
            receipt.setEmailSentAt(LocalDateTime.now());
            receipt.setEmailError("Email service not configured");
            receipt.setStatus(Receipt.ReceiptStatus.SENT);
            receiptRepository.save(receipt);
            
            return new EmailSendResult(false, "Email service not configured", LocalDateTime.now());
        }
        
        String email = recipientEmail != null ? recipientEmail : receipt.getCustomerEmail();
        if (email == null || email.isBlank()) {
            throw new ApiException(400, "No email address provided");
        }
        
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");
            
            helper.setTo(email);
            helper.setSubject("Receipt " + receipt.getReceiptNumber() + " from " + receipt.getBusinessName());
            helper.setText(buildEmailBody(receipt), true);
            
            mailSender.send(message);
            
            // Update receipt
            receipt.setEmailSent(true);
            receipt.setEmailSentAt(LocalDateTime.now());
            receipt.setEmailError(null);
            receipt.setStatus(Receipt.ReceiptStatus.SENT);
            receiptRepository.save(receipt);
            
            logger.info("Sent receipt email {} to {}", receiptNumber, email);
            
            return new EmailSendResult(true, "Email sent successfully", LocalDateTime.now());
            
        } catch (MessagingException | MailException e) {
            logger.error("Failed to send receipt email", e);
            
            // Update error
            receipt.setEmailError(e.getMessage());
            receipt.setStatus(Receipt.ReceiptStatus.FAILED);
            receiptRepository.save(receipt);
            
            throw new ApiException(500, "Failed to send email: " + e.getMessage());
        }
    }

    @Transactional(readOnly = true)
    public ReceiptResponse getReceiptByNumber(String receiptNumber) {
        Receipt receipt = receiptRepository.findByReceiptNumber(receiptNumber)
                .orElseThrow(() -> new ApiException(404, "Receipt not found"));
        return toResponse(receipt);
    }

    @Transactional(readOnly = true)
    public ReceiptsResponse getReceiptsByCustomerEmail(String email) {
        List<Receipt> receipts = receiptRepository.findByCustomerEmailOrderByCreatedAtDesc(email);
        List<ReceiptResponse> responses = receipts.stream().map(this::toResponse).toList();
        return new ReceiptsResponse(responses, responses.size());
    }

    @Transactional(readOnly = true)
    public ReceiptsResponse getReceiptsByBusinessId(String businessId) {
        List<Receipt> receipts = receiptRepository.findByBusinessIdOrderByCreatedAtDesc(businessId);
        List<ReceiptResponse> responses = receipts.stream().map(this::toResponse).toList();
        return new ReceiptsResponse(responses, responses.size());
    }

    @Transactional(readOnly = true)
    public Optional<ReceiptResponse> getReceiptByOrderId(String orderId) {
        return receiptRepository.findByOrderId(orderId).map(this::toResponse);
    }

    @Transactional
    public ReceiptResponse markAsViewed(String receiptNumber) {
        Receipt receipt = receiptRepository.findByReceiptNumber(receiptNumber)
                .orElseThrow(() -> new ApiException(404, "Receipt not found"));
        
        if (!receipt.getInAppViewed()) {
            receipt.setInAppViewed(true);
            receipt.setInAppViewedAt(LocalDateTime.now());
            if (receipt.getStatus() == Receipt.ReceiptStatus.GENERATED) {
                receipt.setStatus(Receipt.ReceiptStatus.VIEWED);
            }
            receipt = receiptRepository.save(receipt);
            logger.info("Marked receipt {} as viewed", receiptNumber);
        }
        
        return toResponse(receipt);
    }

    @Transactional(readOnly = true)
    public ReceiptSummary getReceiptSummary(String businessId) {
        List<Receipt> receipts = businessId != null 
            ? receiptRepository.findByBusinessIdOrderByCreatedAtDesc(businessId)
            : receiptRepository.findAll();
        
        long total = receipts.size();
        long sent = receipts.stream().filter(r -> r.getEmailSent()).count();
        long pending = receipts.stream().filter(r -> r.getStatus() == Receipt.ReceiptStatus.GENERATED).count();
        long failed = receipts.stream().filter(r -> r.getStatus() == Receipt.ReceiptStatus.FAILED).count();
        BigDecimal totalAmount = receipts.stream()
                .map(Receipt::getTotalAmount)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        
        return new ReceiptSummary(total, sent, pending, failed, totalAmount);
    }

    private String buildEmailBody(Receipt receipt) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MMM dd, yyyy HH:mm");
        StringBuilder html = new StringBuilder();
        
        html.append("<!DOCTYPE html>");
        html.append("<html><head><style>");
        html.append("body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }");
        html.append(".container { max-width: 600px; margin: 0 auto; padding: 20px; }");
        html.append(".header { background: #3b82f6; color: white; padding: 20px; text-align: center; }");
        html.append(".content { background: #f9fafb; padding: 20px; }");
        html.append(".receipt-info { background: white; padding: 15px; margin: 10px 0; border-radius: 5px; }");
        html.append(".label { font-weight: bold; color: #666; }");
        html.append(".value { color: #000; }");
        html.append(".total { font-size: 24px; font-weight: bold; color: #3b82f6; margin: 20px 0; }");
        html.append(".footer { text-align: center; color: #666; font-size: 12px; padding: 20px; }");
        html.append("</style></head><body>");
        
        html.append("<div class='container'>");
        html.append("<div class='header'>");
        html.append("<h1>Payment Receipt</h1>");
        html.append("<p>").append(receipt.getBusinessName()).append("</p>");
        html.append("</div>");
        
        html.append("<div class='content'>");
        html.append("<div class='receipt-info'>");
        html.append("<p><span class='label'>Receipt Number:</span> <span class='value'>").append(receipt.getReceiptNumber()).append("</span></p>");
        html.append("<p><span class='label'>Date:</span> <span class='value'>").append(receipt.getPaymentDate().format(formatter)).append("</span></p>");
        
        if (receipt.getCustomerName() != null) {
            html.append("<p><span class='label'>Customer:</span> <span class='value'>").append(receipt.getCustomerName()).append("</span></p>");
        }
        
        if (receipt.getPaymentMethod() != null) {
            html.append("<p><span class='label'>Payment Method:</span> <span class='value'>").append(receipt.getPaymentMethod()).append("</span></p>");
        }
        
        if (receipt.getPaymentReference() != null) {
            html.append("<p><span class='label'>Reference:</span> <span class='value'>").append(receipt.getPaymentReference()).append("</span></p>");
        }
        
        html.append("</div>");
        
        // Items
        if (receipt.getItems() != null) {
            html.append("<div class='receipt-info'>");
            html.append("<h3>Items</h3>");
            try {
                List<?> items = objectMapper.readValue(receipt.getItems(), List.class);
                for (Object item : items) {
                    html.append("<p>").append(item.toString()).append("</p>");
                }
            } catch (JsonProcessingException e) {
                logger.error("Failed to parse receipt items", e);
            }
            html.append("</div>");
        }
        
        // Totals
        html.append("<div class='receipt-info'>");
        if (receipt.getSubtotal() != null) {
            html.append("<p><span class='label'>Subtotal:</span> <span class='value'>").append(receipt.getCurrency()).append(" ").append(receipt.getSubtotal()).append("</span></p>");
        }
        if (receipt.getTaxAmount() != null && receipt.getTaxAmount().compareTo(BigDecimal.ZERO) > 0) {
            html.append("<p><span class='label'>Tax:</span> <span class='value'>").append(receipt.getCurrency()).append(" ").append(receipt.getTaxAmount()).append("</span></p>");
        }
        if (receipt.getServiceFee() != null && receipt.getServiceFee().compareTo(BigDecimal.ZERO) > 0) {
            html.append("<p><span class='label'>Service Fee:</span> <span class='value'>").append(receipt.getCurrency()).append(" ").append(receipt.getServiceFee()).append("</span></p>");
        }
        html.append("<p class='total'>Total: ").append(receipt.getCurrency()).append(" ").append(receipt.getTotalAmount()).append("</p>");
        html.append("</div>");
        
        if (receipt.getNotes() != null) {
            html.append("<div class='receipt-info'>");
            html.append("<p><span class='label'>Notes:</span></p>");
            html.append("<p>").append(receipt.getNotes()).append("</p>");
            html.append("</div>");
        }
        
        html.append("</div>");
        
        html.append("<div class='footer'>");
        html.append("<p>Thank you for your business!</p>");
        html.append("<p>Powered by ScanIT - Digital Receipts</p>");
        html.append("</div>");
        
        html.append("</div>");
        html.append("</body></html>");
        
        return html.toString();
    }

    private ReceiptResponse toResponse(Receipt receipt) {
        List<ReceiptItem> items = null;
        if (receipt.getItems() != null) {
            try {
                items = objectMapper.readValue(receipt.getItems(), 
                    objectMapper.getTypeFactory().constructCollectionType(List.class, ReceiptItem.class));
            } catch (JsonProcessingException e) {
                logger.error("Failed to parse receipt items", e);
            }
        }
        
        return new ReceiptResponse(
            receipt.getId(),
            receipt.getReceiptNumber(),
            receipt.getOrderId(),
            receipt.getTicketId(),
            receipt.getQuickPaymentId(),
            receipt.getDevicePaymentId(),
            receipt.getBusinessId(),
            receipt.getBusinessName(),
            receipt.getMerchantId(),
            receipt.getCustomerName(),
            receipt.getCustomerEmail(),
            receipt.getCustomerPhone(),
            receipt.getAmount(),
            receipt.getCurrency(),
            receipt.getPaymentMethod(),
            receipt.getPaymentReference(),
            receipt.getPaymentDate(),
            items,
            receipt.getSubtotal(),
            receipt.getTaxAmount(),
            receipt.getServiceFee(),
            receipt.getTotalAmount(),
            receipt.getStatus().name(),
            receipt.getEmailSent(),
            receipt.getEmailSentAt(),
            receipt.getInAppViewed(),
            receipt.getInAppViewedAt(),
            receipt.getPdfGenerated(),
            receipt.getPdfUrl(),
            receipt.getNotes(),
            receipt.getCreatedAt()
        );
    }
}
