CREATE TABLE qr_scan_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id VARCHAR(64) NOT NULL,
    qr_token VARCHAR(128) NOT NULL DEFAULT '',
    scanned_at TIMESTAMP NOT NULL,
    user_agent VARCHAR(512) NOT NULL DEFAULT ''
);

CREATE INDEX idx_qr_scan_events_scanned_at ON qr_scan_events(scanned_at);
CREATE INDEX idx_qr_scan_events_business_id ON qr_scan_events(business_id);
