-- Hot-path indexes for multi-tenant order/scan load
CREATE INDEX IF NOT EXISTS idx_orders_business_created_at
    ON orders (business_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_orders_business_status
    ON orders (business_id, status);

CREATE INDEX IF NOT EXISTS idx_qr_scan_events_business_ua_scanned
    ON qr_scan_events (business_id, user_agent, scanned_at DESC);

CREATE INDEX IF NOT EXISTS idx_qr_scan_events_business_token_ua_scanned
    ON qr_scan_events (business_id, qr_token, user_agent, scanned_at DESC);

CREATE INDEX IF NOT EXISTS idx_ticket_scans_scanned_at
    ON ticket_scans (scanned_at);

CREATE INDEX IF NOT EXISTS idx_tickets_event_attendee
    ON tickets (event_name)
    WHERE master_ticket_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_payment_intents_provider_ref
    ON payment_intents (provider_reference)
    WHERE provider_reference IS NOT NULL AND provider_reference <> '';

-- Durable outbox for async side effects (WS, audit metrics, receipts)
CREATE TABLE IF NOT EXISTS outbox_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type      VARCHAR(64)  NOT NULL,
    channel         VARCHAR(128) NOT NULL DEFAULT '',
    business_id     VARCHAR(64)  NOT NULL DEFAULT '',
    payload_json    TEXT         NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    processed_at    TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_outbox_events_pending
    ON outbox_events (created_at)
    WHERE processed_at IS NULL;
