CREATE TABLE IF NOT EXISTS cookie_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    choice VARCHAR(16) NOT NULL,
    client_id VARCHAR(120),
    source VARCHAR(255),
    path VARCHAR(255),
    actor_subject VARCHAR(255),
    actor_email VARCHAR(255),
    user_agent VARCHAR(512),
    ip_address VARCHAR(64),
    consented_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cookie_consents_consented_at ON cookie_consents(consented_at);
CREATE INDEX IF NOT EXISTS idx_cookie_consents_actor_subject ON cookie_consents(actor_subject);
CREATE INDEX IF NOT EXISTS idx_cookie_consents_client_id ON cookie_consents(client_id);
