package com.scanny.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.scanny.dto.ReceiptDtos.*;
import com.scanny.entity.Receipt;
import com.scanny.exception.ApiException;
import com.scanny.repository.ReceiptRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Service
public class ReceiptService {

    private static final Logger logger = LoggerFactory.getLogger(ReceiptService.class);
    
    private final ReceiptRepository receiptRepository;
    private final ObjectMapper objectMapper;

    public ReceiptService(ReceiptRepository receiptRepository, ObjectMapper objectMapper) {
        this.receiptRepository = receiptRepository;
        this.objectMapper = objectMapper;
    }

    @Transactional
    public ReceiptResponse generateReceipt(GenerateReceiptRequest request) {
        // Validate request
        if (request.businessId() == null || request.businessId().isBlank()) {
            throw new ApiException(400, "Business ID is required");
        }
        if (request.amount() == null || request.amount().compareTo(BigDecimal.ZERO) <= 0) {
            throw new ApiException(400, "Amount must be greater than zero");
        }

        // Create receipt entity
        Receipt receipt = new Receipt();
        
        // Receipt number will be generated by database trigger
        // Do NOT set receiptNumber here - let the DB trigger handle it
        
        // Payment references
        receipt.setOrderId(request.orderId());
        receipt.setTicketId(request.ticketId());
        receipt.setQuickPaymentId(request.quickPaymentId());
        receipt.setDevicePaymentId(request.devicePaymentId());
        
        // Business details
        receipt.setBusinessId(request.businessId());
        receipt.setBusinessName(request.businessName() != null ? request.businessName() : "Unknown Business");
        receipt.setMerchantId(request.merchantId() != null ? request.merchantId() : request.businessId());
        
        // Customer details
        receipt.setCustomerName(request.customerName());
        receipt.setCustomerEmail(request.customerEmail());
        receipt.setCustomerPhone(request.customerPhone());
        
        // Payment details
        receipt.setAmount(request.amount());
        receipt.setCurrency(request.currency() != null ? request.currency() : "UGX");
        receipt.setPaymentMethod(request.paymentMethod());
        receipt.setPaymentReference(request.paymentReference());
        receipt.setPaymentDate(LocalDateTime.now());
        
        // Items (convert to JSON)
        if (request.items() != null && !request.items().isEmpty()) {
            try {
                receipt.setItems(objectMapper.writeValueAsString(request.items()));
            } catch (JsonProcessingException e) {
                logger.error("Failed to serialize receipt items", e);
            }
        }
        
        // Calculate totals
        BigDecimal subtotal = request.subtotal() != null ? request.subtotal() : request.amount();
        BigDecimal taxAmount = request.taxAmount() != null ? request.taxAmount() : BigDecimal.ZERO;
        BigDecimal serviceFee = request.serviceFee() != null ? request.serviceFee() : BigDecimal.ZERO;
        BigDecimal totalAmount = subtotal.add(taxAmount).add(serviceFee);
        
        receipt.setSubtotal(subtotal);
        receipt.setTaxAmount(taxAmount);
        receipt.setServiceFee(serviceFee);
        receipt.setTotalAmount(totalAmount);
        
        // Metadata
        receipt.setNotes(request.notes());
        receipt.setStatus(Receipt.ReceiptStatus.GENERATED);
        
        // Save receipt - flush to get the generated receipt number from DB
        receipt = receiptRepository.saveAndFlush(receipt);
        
        // Refresh to get the generated receipt number from the database trigger
        receiptRepository.refresh(receipt);
        
        // Receipt emailing is intentionally disabled. Email is reserved for account-creation flows.
        if (Boolean.TRUE.equals(request.sendEmail())) {
            logger.info("Receipt email request ignored for {} because receipt emailing is disabled", receipt.getReceiptNumber());
        }
        
        logger.info("Generated receipt {} for business {}", receipt.getReceiptNumber(), receipt.getBusinessId());
        
        return toResponse(receipt);
    }

    @Transactional
    public EmailSendResult sendReceiptEmail(String receiptNumber, String recipientEmail) {
        if (receiptNumber == null || receiptNumber.isBlank()) {
            throw new ApiException(400, "Receipt number is required");
        }
        logger.info("Receipt email request ignored for {} because receipt emailing is disabled", receiptNumber);
        return new EmailSendResult(
            false,
            "Receipt emailing is disabled. Email is reserved for account creation only.",
            LocalDateTime.now()
        );
    }

    @Transactional(readOnly = true)
    public ReceiptResponse getReceiptByNumber(String receiptNumber) {
        Receipt receipt = receiptRepository.findByReceiptNumber(receiptNumber)
                .orElseThrow(() -> new ApiException(404, "Receipt not found"));
        return toResponse(receipt);
    }

    @Transactional(readOnly = true)
    public ReceiptsResponse getReceiptsByCustomerEmail(String email) {
        List<Receipt> receipts = receiptRepository.findByCustomerEmailOrderByCreatedAtDesc(email);
        List<ReceiptResponse> responses = receipts.stream().map(this::toResponse).toList();
        return new ReceiptsResponse(responses, responses.size());
    }

    @Transactional(readOnly = true)
    public ReceiptsResponse getReceiptsByBusinessId(String businessId) {
        List<Receipt> receipts = receiptRepository.findByBusinessIdOrderByCreatedAtDesc(businessId);
        List<ReceiptResponse> responses = receipts.stream().map(this::toResponse).toList();
        return new ReceiptsResponse(responses, responses.size());
    }

    @Transactional(readOnly = true)
    public Optional<ReceiptResponse> getReceiptByOrderId(String orderId) {
        return receiptRepository.findByOrderId(orderId).map(this::toResponse);
    }

    @Transactional
    public ReceiptResponse markAsViewed(String receiptNumber) {
        Receipt receipt = receiptRepository.findByReceiptNumber(receiptNumber)
                .orElseThrow(() -> new ApiException(404, "Receipt not found"));
        
        if (!receipt.getInAppViewed()) {
            receipt.setInAppViewed(true);
            receipt.setInAppViewedAt(LocalDateTime.now());
            if (receipt.getStatus() == Receipt.ReceiptStatus.GENERATED) {
                receipt.setStatus(Receipt.ReceiptStatus.VIEWED);
            }
            receipt = receiptRepository.save(receipt);
            logger.info("Marked receipt {} as viewed", receiptNumber);
        }
        
        return toResponse(receipt);
    }

    @Transactional(readOnly = true)
    public ReceiptSummary getReceiptSummary(String businessId) {
        List<Receipt> receipts = businessId != null 
            ? receiptRepository.findByBusinessIdOrderByCreatedAtDesc(businessId)
            : receiptRepository.findAll();
        
        long total = receipts.size();
        long sent = receipts.stream().filter(r -> r.getEmailSent()).count();
        long pending = receipts.stream().filter(r -> r.getStatus() == Receipt.ReceiptStatus.GENERATED).count();
        long failed = receipts.stream().filter(r -> r.getStatus() == Receipt.ReceiptStatus.FAILED).count();
        BigDecimal totalAmount = receipts.stream()
                .map(Receipt::getTotalAmount)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        
        return new ReceiptSummary(total, sent, pending, failed, totalAmount);
    }

    private ReceiptResponse toResponse(Receipt receipt) {
        List<ReceiptItem> items = null;
        if (receipt.getItems() != null) {
            try {
                items = objectMapper.readValue(receipt.getItems(), 
                    objectMapper.getTypeFactory().constructCollectionType(List.class, ReceiptItem.class));
            } catch (JsonProcessingException e) {
                logger.error("Failed to parse receipt items", e);
            }
        }
        
        return new ReceiptResponse(
            receipt.getId(),
            receipt.getReceiptNumber(),
            receipt.getOrderId(),
            receipt.getTicketId(),
            receipt.getQuickPaymentId(),
            receipt.getDevicePaymentId(),
            receipt.getBusinessId(),
            receipt.getBusinessName(),
            receipt.getMerchantId(),
            receipt.getCustomerName(),
            receipt.getCustomerEmail(),
            receipt.getCustomerPhone(),
            receipt.getAmount(),
            receipt.getCurrency(),
            receipt.getPaymentMethod(),
            receipt.getPaymentReference(),
            receipt.getPaymentDate(),
            items,
            receipt.getSubtotal(),
            receipt.getTaxAmount(),
            receipt.getServiceFee(),
            receipt.getTotalAmount(),
            receipt.getStatus().name(),
            receipt.getEmailSent(),
            receipt.getEmailSentAt(),
            receipt.getInAppViewed(),
            receipt.getInAppViewedAt(),
            receipt.getPdfGenerated(),
            receipt.getPdfUrl(),
            receipt.getNotes(),
            receipt.getCreatedAt()
        );
    }
}
