spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:file:./data/scanny;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

scanny:
  scan-base-url: ${SCAN_BASE_URL:http://localhost:5173}

keycloak:
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
